#import <Foundation/Foundation.h>
#import "SWGInlineResponse200.h"
#import "SWGErrorModel.h"
#import "SWGInlineResponse2004.h"
#import "SWGAccommodation.h"
#import "SWGApi.h"

/**
* Scubawhere API Documentation
* This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
*
* OpenAPI spec version: 1.0.0
* Contact: bryan@scubawhere.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGAccommodationApi: NSObject <SWGApi>

extern NSString* kSWGAccommodationApiErrorDomain;
extern NSInteger kSWGAccommodationApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// 
/// Create an accommodation
///
/// @param name Name of the type of accommodation
/// @param capacity Number of beds in the accommodation
/// @param basePrices Price of the accommodation and the dates of when the price is applicable
/// @param _description Description of the accommodation (optional)
/// 
///  code:200 message:"Success (Resource was created)",
///  code:404 message:"Not found (No accommodation exists with the ID provided)",
///  code:422 message:"Unprocessable Entity (One or more of the parameters was invalid)"
///
/// @return SWGInlineResponse200*
-(NSNumber*) addAccommodationWithName: (NSString*) name
    capacity: (NSNumber*) capacity
    basePrices: (NSNumber*) basePrices
    _description: (NSString*) _description
    completionHandler: (void (^)(SWGInlineResponse200* output, NSError* error)) handler;


/// Delete an accommodation by ID
/// 
///
/// @param body ID of the accommodation
/// 
///  code:200 message:"Success (Resource was deleted)",
///  code:404 message:"Not found (No accommodation exists with the ID provided)"
///
/// @return SWGInlineResponse200*
-(NSNumber*) deleteAccommodationWithBody: (NSNumber*) body
    completionHandler: (void (^)(SWGInlineResponse200* output, NSError* error)) handler;


/// Create a new agent
/// 
///
/// @param _id 
/// @param name 
/// @param branchName 
/// @param branchAddress 
/// @param branchPhone 
/// @param branchEmail 
/// @param commission 
/// @param terms 
/// @param website  (optional)
/// @param billingAddress  (optional)
/// @param billingPhone  (optional)
/// @param billingEmail  (optional)
/// 
///  code:200 message:"Success (Resource created)",
///  code:404 message:"Not found (No agent with the ID provided)",
///  code:422 message:"Unprocessable Entity (One or more parameter was invalid)"
///
/// @return SWGInlineResponse2004*
-(NSNumber*) editAgentWithId: (NSNumber*) _id
    name: (NSNumber*) name
    branchName: (NSString*) branchName
    branchAddress: (NSString*) branchAddress
    branchPhone: (NSString*) branchPhone
    branchEmail: (NSString*) branchEmail
    commission: (NSNumber*) commission
    terms: (NSString*) terms
    website: (NSString*) website
    billingAddress: (NSString*) billingAddress
    billingPhone: (NSString*) billingPhone
    billingEmail: (NSString*) billingEmail
    completionHandler: (void (^)(SWGInlineResponse2004* output, NSError* error)) handler;


/// Get all the accommodations matching a filter
/// Get all the accommodations and their bookings between certain dates and / or an accommodation id
///
/// @param before The date for the upper boundary of the dates (optional)
/// @param after The date for the lower boundary of the dates (optional)
/// @param accommodationId ID Accommodation to filter by (optional)
/// 
///  code:200 message:"Success (Resource was found)",
///  code:404 message:"Not found (No accommodation with the ID provided)",
///  code:422 message:"Unprocessable Entity (One or more parameters was invalid)"
///
/// @return SWGInlineResponse200*
-(NSNumber*) filterAccommodationWithBefore: (NSDate*) before
    after: (NSDate*) after
    accommodationId: (NSNumber*) accommodationId
    completionHandler: (void (^)(SWGInlineResponse200* output, NSError* error)) handler;


/// 
/// Retrieve an accommodation by ID
///
/// @param _id ID of the accommodation to be retrieved
/// 
///  code:200 message:"Success (Resource was found)",
///  code:404 message:"Not found (No accommodation with the ID provided)",
///  code:422 message:"Unprocessable Entity (ID was not provided)"
///
/// @return SWGInlineResponse200*
-(NSNumber*) findAccommodationWithId: (NSArray<NSNumber*>*) _id
    completionHandler: (void (^)(SWGInlineResponse200* output, NSError* error)) handler;


/// 
/// Retrieve all accommodation
///
/// 
///  code:200 message:"Success (Resource was found)"
///
/// @return NSArray<SWGAccommodation>*
-(NSNumber*) getAllAccommodationsWithCompletionHandler: 
    (void (^)(NSArray<SWGAccommodation>* output, NSError* error)) handler;


/// Retrieve all accommodation including any deleted models
/// 
///
/// 
///  code:200 message:"Success (Resource was found)"
///
/// @return NSArray<SWGAccommodation>*
-(NSNumber*) getAllWithTrashedAccommodationsWithCompletionHandler: 
    (void (^)(NSArray<SWGAccommodation>* output, NSError* error)) handler;


/// Update an Accommodation
/// Updates the accommodation by id using the specified fields
///
/// @param _id ID of the Accommodation to be updated
/// @param name Name of the Accommodation (optional)
/// @param capacity Number of rooms the accommodation holds (optional)
/// 
///  code:200 message:"Success (Resource was updated)",
///  code:404 message:"Not found (No accommodation exists with the ID provided)",
///  code:422 message:"Unprocessable Entity (One or more of the parameters was invalid)"
///
/// @return SWGInlineResponse200*
-(NSNumber*) updateAccommodationWithId: (NSNumber*) _id
    name: (NSString*) name
    capacity: (NSNumber*) capacity
    completionHandler: (void (^)(SWGInlineResponse200* output, NSError* error)) handler;



@end
