#import <Foundation/Foundation.h>
#import "SWGInlineResponse2002.h"
#import "SWGErrorModel.h"
#import "SWGInlineResponse2003.h"
#import "SWGInlineResponse2001.h"
#import "SWGAddon.h"
#import "SWGApi.h"

/**
* Scubawhere API Documentation
* This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
*
* OpenAPI spec version: 1.0.0
* Contact: bryan@scubawhere.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGAddonApi: NSObject <SWGApi>

extern NSString* kSWGAddonApiErrorDomain;
extern NSInteger kSWGAddonApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Create a new addon
/// 
///
/// @param name Name of the type of addon
/// @param basePrices Prices for addon
/// @param _description Description of the addon (optional)
/// 
///  code:200 message:"Success (Resource was created)",
///  code:422 message:"Unprocessable Entity (One or more of the parameters was invalid)"
///
/// @return SWGInlineResponse2002*
-(NSNumber*) addAddonWithName: (NSString*) name
    basePrices: (NSNumber*) basePrices
    _description: (NSString*) _description
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error)) handler;


/// Delete an addon by ID
/// 
///
/// @param body ID of the Addon (optional)
/// 
///  code:200 message:"Success (Resource was deleted)",
///  code:404 message:"Not found (No addon exists with the ID provided)"
///
/// @return SWGInlineResponse2003*
-(NSNumber*) deleteAddonWithBody: (NSNumber*) body
    completionHandler: (void (^)(SWGInlineResponse2003* output, NSError* error)) handler;


/// Retrieve an addon by ID
/// 
///
/// @param _id ID of the addon to be retrieved
/// 
///  code:200 message:"Success (Resource was found)",
///  code:404 message:"Not found (No addon exists with the ID provided)",
///  code:422 message:"Unprocessable Entity (ID was not provided)"
///
/// @return SWGInlineResponse2001*
-(NSNumber*) getAddonWithId: (NSNumber*) _id
    completionHandler: (void (^)(SWGInlineResponse2001* output, NSError* error)) handler;


/// Retrieve all addons
/// 
///
/// 
///  code:200 message:"Success (Resource was found)"
///
/// @return NSArray<SWGAddon>*
-(NSNumber*) getAllAddonsWithCompletionHandler: 
    (void (^)(NSArray<SWGAddon>* output, NSError* error)) handler;


/// Retrieve all addons including any deleted models
/// 
///
/// 
///  code:200 message:"Success (Resource was found)"
///
/// @return NSArray<SWGAddon>*
-(NSNumber*) getAllWithTrashedAddonsWithCompletionHandler: 
    (void (^)(NSArray<SWGAddon>* output, NSError* error)) handler;


/// Update an Addon
/// Updates the addon by id using the specified fields
///
/// @param _id ID of the Addon to be updated
/// @param name Name of the Addon (optional)
/// @param _description Description of the Addon (optional)
/// 
///  code:200 message:"Success (Resource was updated)",
///  code:404 message:"Not found (No addon exists with the ID provided)",
///  code:422 message:"Unprocessable Entity (One or more of the parameters was invalid)"
///
/// @return SWGInlineResponse2002*
-(NSNumber*) updateAddonWithId: (NSNumber*) _id
    name: (NSString*) name
    _description: (NSString*) _description
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error)) handler;



@end
