#import <Foundation/Foundation.h>
#import "SWGInlineResponse20027.h"
#import "SWGErrorModel.h"
#import "SWGInlineResponse2003.h"
#import "SWGInlineResponse20028.h"
#import "SWGCourse.h"
#import "SWGApi.h"

/**
* Scubawhere API Documentation
* This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
*
* OpenAPI spec version: 1.0.0
* Contact: bryan@scubawhere.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGCourseApi: NSObject <SWGApi>

extern NSString* kSWGCourseApiErrorDomain;
extern NSInteger kSWGCourseApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Create a new course
/// 
///
/// @param name 
/// @param _description 
/// @param capacity 
/// @param prices 
/// @param certificateId  (optional)
/// @param tickets  (optional)
/// @param trainings  (optional)
/// 
///  code:200 message:"Success (Resource created)",
///  code:422 message:"Unprocessable Entity (One or more parameter was invalid)"
///
/// @return SWGInlineResponse20027*
-(NSNumber*) createCourseWithName: (NSString*) name
    _description: (NSString*) _description
    capacity: (NSNumber*) capacity
    prices: (NSArray<NSNumber*>*) prices
    certificateId: (NSNumber*) certificateId
    tickets: (NSArray<NSNumber*>*) tickets
    trainings: (NSArray<NSNumber*>*) trainings
    completionHandler: (void (^)(SWGInlineResponse20027* output, NSError* error)) handler;


/// Delete a course by ID
/// 
///
/// @param _id 
/// 
///  code:200 message:"Success (Resource was deleted)",
///  code:404 message:"Not found (No boatroom exists with the ID provided)"
///
/// @return SWGInlineResponse2003*
-(NSNumber*) deleteCourseWithId: (NSNumber*) _id
    completionHandler: (void (^)(SWGInlineResponse2003* output, NSError* error)) handler;


/// Update a course by ID
/// 
///
/// @param _id 
/// @param name 
/// @param _description 
/// @param capacity 
/// @param certificateId  (optional)
/// @param tickets  (optional)
/// @param trainings  (optional)
/// 
///  code:200 message:"Success (Resource created)",
///  code:404 message:"Not found (No boatroom with the ID provided)",
///  code:422 message:"Unprocessable Entity (One or more parameter was invalid)"
///
/// @return SWGInlineResponse20028*
-(NSNumber*) editCourseWithId: (NSNumber*) _id
    name: (NSString*) name
    _description: (NSString*) _description
    capacity: (NSNumber*) capacity
    certificateId: (NSNumber*) certificateId
    tickets: (NSArray<NSNumber*>*) tickets
    trainings: (NSArray<NSNumber*>*) trainings
    completionHandler: (void (^)(SWGInlineResponse20028* output, NSError* error)) handler;


/// Retrieve all courses including any deleted models
/// 
///
/// 
///  code:200 message:"Success"
///
/// @return NSArray<SWGCourse>*
-(NSNumber*) getAllCoursesWithCompletionHandler: 
    (void (^)(NSArray<SWGCourse>* output, NSError* error)) handler;


/// Retrieve all courses including any deleted models
/// 
///
/// 
///  code:200 message:"Success"
///
/// @return NSArray<SWGCourse>*
-(NSNumber*) getAllWithTrashedCoursesWithCompletionHandler: 
    (void (^)(NSArray<SWGCourse>* output, NSError* error)) handler;


/// Retrieve a course by ID
/// 
///
/// @param _id  (optional)
/// 
///  code:200 message:"Success (Resource was found)",
///  code:404 message:"Not found (No course exists with the ID provided)",
///  code:422 message:"Unproccessable Entity (One or more of the parameters was invalid)"
///
/// @return SWGInlineResponse20027*
-(NSNumber*) getCourseWithId: (NSNumber*) _id
    completionHandler: (void (^)(SWGInlineResponse20027* output, NSError* error)) handler;



@end
