#import <Foundation/Foundation.h>
#import "SWGErrorModel.h"
#import "SWGTraining.h"
#import "SWGInlineResponse20021.h"
#import "SWGInlineResponse2003.h"
#import "SWGInlineResponse20022.h"
#import "SWGApi.h"

/**
* Scubawhere API Documentation
* This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
*
* OpenAPI spec version: 1.0.0
* Contact: bryan@scubawhere.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGClassApi: NSObject <SWGApi>

extern NSString* kSWGClassApiErrorDomain;
extern NSInteger kSWGClassApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Retrieve a class by ID
/// 
///
/// @param _id 
/// 
///  code:200 message:"Success (Resource Found)",
///  code:404 message:"Not Found (No timetable with that ID exists)",
///  code:422 message:"Unprocessable Entity (One or more parameter was invalid)"
///
/// @return SWGTraining*
-(NSNumber*) classGetWithId: (NSNumber*) _id
    completionHandler: (void (^)(SWGTraining* output, NSError* error)) handler;


/// Create a new class
/// 
///
/// @param name 
/// @param duration 
/// @param _description  (optional)
/// 
///  code:200 message:"Success (Resource created)",
///  code:422 message:"Unprocessable Entity (One or more parameter was invalid)"
///
/// @return SWGInlineResponse20021*
-(NSNumber*) createClassWithName: (NSString*) name
    duration: (NSNumber*) duration
    _description: (NSString*) _description
    completionHandler: (void (^)(SWGInlineResponse20021* output, NSError* error)) handler;


/// Delete a class by ID
/// 
///
/// @param _id 
/// 
///  code:200 message:"Success (Resource was deleted)",
///  code:404 message:"Not found (No package exists with the ID provided)"
///
/// @return SWGInlineResponse2003*
-(NSNumber*) deleteClassWithId: (NSNumber*) _id
    completionHandler: (void (^)(SWGInlineResponse2003* output, NSError* error)) handler;


/// Update a class by ID
/// 
///
/// @param _id 
/// @param name 
/// @param duration 
/// @param _description  (optional)
/// 
///  code:200 message:"Success (Resource created)",
///  code:404 message:"Not found (No boatroom with the ID provided)",
///  code:422 message:"Unprocessable Entity (One or more parameter was invalid)"
///
/// @return SWGInlineResponse20022*
-(NSNumber*) editClassWithId: (NSNumber*) _id
    name: (NSString*) name
    duration: (NSNumber*) duration
    _description: (NSString*) _description
    completionHandler: (void (^)(SWGInlineResponse20022* output, NSError* error)) handler;


/// Retrieve all classes including any deleted models
/// 
///
/// 
///  code:200 message:"Success"
///
/// @return NSArray<SWGTraining>*
-(NSNumber*) getAllClassWithCompletionHandler: 
    (void (^)(NSArray<SWGTraining>* output, NSError* error)) handler;


/// Retrieve all classes including any deleted models
/// 
///
/// 
///  code:200 message:"Success"
///
/// @return NSArray<SWGTraining>*
-(NSNumber*) getAllWithTrashedClassWithCompletionHandler: 
    (void (^)(NSArray<SWGTraining>* output, NSError* error)) handler;



@end
