#import <Foundation/Foundation.h>
#import "SWGErrorModel.h"
#import "SWGInlineResponse20023.h"
#import "SWGInlineResponse20024.h"
#import "SWGInlineResponse20025.h"
#import "SWGInlineResponse20026.h"
#import "SWGApi.h"

/**
* Scubawhere API Documentation
* This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
*
* OpenAPI spec version: 1.0.0
* Contact: bryan@scubawhere.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGCompanyApi: NSObject <SWGApi>

extern NSString* kSWGCompanyApiErrorDomain;
extern NSInteger kSWGCompanyApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Attach a location to a company
/// 
///
/// @param name  (optional)
/// @param _description  (optional)
/// @param latitude  (optional)
/// @param longitude  (optional)
/// 
///  code:200 message:"Success (Resource was found)",
///  code:422 message:"Unproccessable Entity (One or more of the parameters was invalid)"
///
/// @return SWGInlineResponse20023*
-(NSNumber*) attachLocationsWithName: (NSString*) name
    _description: (NSString*) _description
    latitude: (NSNumber*) latitude
    longitude: (NSNumber*) longitude
    completionHandler: (void (^)(SWGInlineResponse20023* output, NSError* error)) handler;


/// Retrieve the locations this Dive Centre uses
/// 
///
/// @param latitude 
/// @param longitude 
/// @param limit  (optional)
/// 
///  code:200 message:"Success (Resource was found)",
///  code:422 message:"Unproccessable Entity (One or more of the parameters was invalid)"
///
/// @return SWGInlineResponse20024*
-(NSNumber*) getLocationsWithLatitude: (NSString*) latitude
    longitude: (NSString*) longitude
    limit: (NSNumber*) limit
    completionHandler: (void (^)(SWGInlineResponse20024* output, NSError* error)) handler;


/// Retrieve the pick up schedule for a date
/// 
///
/// @param date 
/// 
///  code:200 message:"Success (Resource was found)",
///  code:422 message:"Unproccessable Entity (One or more of the parameters was invalid)"
///
/// @return SWGInlineResponse20025*
-(NSNumber*) getPickupScheduleWithDate: (NSString*) date
    completionHandler: (void (^)(SWGInlineResponse20025* output, NSError* error)) handler;


/// Update the companies information
/// 
///
/// @param _id 
/// @param contact  (optional)
/// @param _description  (optional)
/// @param name  (optional)
/// @param address1  (optional)
/// @param address2  (optional)
/// @param city  (optional)
/// @param county  (optional)
/// @param postcode  (optional)
/// @param countryId  (optional)
/// @param currencyId  (optional)
/// @param businessPhone  (optional)
/// @param businessEmail  (optional)
/// @param vatNumber  (optional)
/// @param registrationNumber  (optional)
/// @param website  (optional)
/// 
///  code:200 message:"Success (Resource was updated)",
///  code:404 message:"Not found (No company exists with the ID provided)",
///  code:422 message:"Unproccessable Entity (One or more of the parameters was invalid)"
///
/// @return SWGInlineResponse20026*
-(NSNumber*) updateCompanyWithId: (NSNumber*) _id
    contact: (NSString*) contact
    _description: (NSString*) _description
    name: (NSString*) name
    address1: (NSString*) address1
    address2: (NSString*) address2
    city: (NSString*) city
    county: (NSString*) county
    postcode: (NSString*) postcode
    countryId: (NSNumber*) countryId
    currencyId: (NSNumber*) currencyId
    businessPhone: (NSString*) businessPhone
    businessEmail: (NSString*) businessEmail
    vatNumber: (NSString*) vatNumber
    registrationNumber: (NSString*) registrationNumber
    website: (NSString*) website
    completionHandler: (void (^)(SWGInlineResponse20026* output, NSError* error)) handler;



@end
