#import <Foundation/Foundation.h>
#import "SWGInlineResponse2012.h"
#import "SWGInlineResponse20039.h"
#import "SWGErrorModel.h"
#import "SWGInlineResponse20038.h"
#import "SWGInlineResponse20037.h"
#import "SWGApi.h"

/**
* Scubawhere API Documentation
* This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
*
* OpenAPI spec version: 1.0.0
* Contact: bryan@scubawhere.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGRefundApi: NSObject <SWGApi>

extern NSString* kSWGRefundApiErrorDomain;
extern NSInteger kSWGRefundApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Create a new refund
/// 
///
/// @param bookingId 
/// @param paymentgatewayId 
/// @param amount 
/// 
///  code:201 message:"Success (Resource created)"
///
/// @return SWGInlineResponse2012*
-(NSNumber*) addRefundWithBookingId: (NSNumber*) bookingId
    paymentgatewayId: (NSNumber*) paymentgatewayId
    amount: (NSNumber*) amount
    completionHandler: (void (^)(SWGInlineResponse2012* output, NSError* error)) handler;


/// Retrieve all refunds that match a filter
/// 
///
/// @param after Date of the earliest payment (optional)
/// @param before Date of the latest payment to be retrieved (optional)
/// 
///  code:200 message:"Success (Resource found)",
///  code:422 message:"Unprocessable Entity (One or more parameter was invalid)"
///
/// @return SWGInlineResponse20039*
-(NSNumber*) filterRefundsWithAfter: (NSDate*) after
    before: (NSDate*) before
    completionHandler: (void (^)(SWGInlineResponse20039* output, NSError* error)) handler;


/// Retrieve all refunds made
/// 
///
/// 
///  code:200 message:"Success"
///
/// @return SWGInlineResponse20038*
-(NSNumber*) getAllRefundsWithCompletionHandler: 
    (void (^)(SWGInlineResponse20038* output, NSError* error)) handler;


/// Retrieve a refund by ID
/// 
///
/// @param _id 
/// 
///  code:200 message:"Success (Resource was found)",
///  code:404 message:"Not found (No payment exists with the ID provided)"
///
/// @return SWGInlineResponse20037*
-(NSNumber*) getRefundWithId: (NSNumber*) _id
    completionHandler: (void (^)(SWGInlineResponse20037* output, NSError* error)) handler;



@end
