#import <Foundation/Foundation.h>
#import "SWGInlineResponse2015.h"
#import "SWGErrorModel.h"
#import "SWGTimetable.h"
#import "SWGApi.h"

/**
* Scubawhere API Documentation
* This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
*
* OpenAPI spec version: 1.0.0
* Contact: bryan@scubawhere.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGTimetableApi: NSObject <SWGApi>

extern NSString* kSWGTimetableApiErrorDomain;
extern NSInteger kSWGTimetableApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Create a new timetable for sessions
/// 
///
/// @param schedule 
/// @param sessionId 
/// @param until  (optional)
/// 
///  code:201 message:"Success (Resource Created)",
///  code:422 message:"Unprocessable Entity (One or more parameter was invalid)"
///
/// @return SWGInlineResponse2015*
-(NSNumber*) addTimetableWithSchedule: (NSString*) schedule
    sessionId: (NSNumber*) sessionId
    until: (NSDate*) until
    completionHandler: (void (^)(SWGInlineResponse2015* output, NSError* error)) handler;


/// Retrieve all of the timetables for sessions
/// 
///
/// 
///  code:200 message:"Success (Resource Found)"
///
/// @return NSArray<SWGTimetable>*
-(NSNumber*) getAllTimetablesWithCompletionHandler: 
    (void (^)(NSArray<SWGTimetable>* output, NSError* error)) handler;


/// Retrieve a timetable by ID
/// 
///
/// @param _id 
/// 
///  code:200 message:"Success (Resource Found)",
///  code:404 message:"Not Found (No timetable with that ID exists)",
///  code:422 message:"Unprocessable Entity (One or more parameter was invalid)"
///
/// @return SWGTimetable*
-(NSNumber*) getTimetableWithId: (NSNumber*) _id
    completionHandler: (void (^)(SWGTimetable* output, NSError* error)) handler;



@end
