#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Scubawhere API Documentation
* This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
*
* OpenAPI spec version: 1.0.0
* Contact: bryan@scubawhere.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

#import "SWGCountry.h"


@protocol SWGCustomer
@end

@interface SWGCustomer : SWGObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* email;

@property(nonatomic) NSString* firstname;

@property(nonatomic) NSString* lastname;

@property(nonatomic) NSNumber* verified;

@property(nonatomic) NSDate* birthday;

@property(nonatomic) NSNumber* gender;

@property(nonatomic) NSString* address1;

@property(nonatomic) NSString* address2;

@property(nonatomic) NSString* city;

@property(nonatomic) NSString* county;

@property(nonatomic) NSString* postcode;

@property(nonatomic) NSNumber* countryId;

@property(nonatomic) NSString* phone;

@property(nonatomic) NSDate* lastDive;

@property(nonatomic) NSNumber* numberOfDives;

@property(nonatomic) NSString* chestSize;

@property(nonatomic) NSString* shoeSize;

@property(nonatomic) NSString* height;

@property(nonatomic) NSString* cylinderSize;

@property(nonatomic) NSString* notes;

@property(nonatomic) NSNumber* unsubscribed;

@property(nonatomic) SWGCountry* country;

@end
