#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Scubawhere API Documentation
* This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
*
* OpenAPI spec version: 1.0.0
* Contact: bryan@scubawhere.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

#import "SWGDateRange.h"
#import "SWGReportEntry.h"
#import "SWGReportEntryTotal.h"


@protocol SWGInlineResponse20040
@end

@interface SWGInlineResponse20040 : SWGObject


@property(nonatomic) SWGDateRange* daterange;

@property(nonatomic) SWGReportEntry* accommodations;

@property(nonatomic) SWGReportEntryTotal* accommodationToal;

@property(nonatomic) SWGReportEntry* addons;

@property(nonatomic) SWGReportEntryTotal* addonsToal;

@property(nonatomic) SWGReportEntry* courses;

@property(nonatomic) SWGReportEntryTotal* coursesToal;

@property(nonatomic) SWGReportEntry* fees;

@property(nonatomic) SWGReportEntryTotal* feesToal;

@property(nonatomic) SWGReportEntry* packages;

@property(nonatomic) SWGReportEntryTotal* packageToal;

@property(nonatomic) SWGReportEntry* tickets;

@property(nonatomic) SWGReportEntryTotal* ticketToal;

@end
